FROM alpine:3.18

# Copie de l’application dans le conteneur
WORKDIR /app
COPY app/ /app/

# Installation de Python 3 et pip
RUN apk add --no-cache python3 py3-pip && \
    pip3 install --break-system-packages -r requirements.txt

# Exposition du port de l’API
EXPOSE 8000
    


CMD [ "uvicorn","main:app", "--host", "0.0.0.0", "--port", "8000" ]
